/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.0 and the 
 *
 * Generated on: 15-Jan-2017 14:34:56
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form II, Second-Order Sections
 * Filter Order      : 5
 * Stable            : Yes
 * Linear Phase      : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\MATLAB7\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.9616076266275,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9100023323578,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.9443110625264,                 0,                 0 
  },
  {
                   1,                -1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,2,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.916526647419,   0.9299038590912 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.813675007231,      0.8263343222 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.8886221250528,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
